# Generated by Django 3.0.2 on 2020-01-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PS4'), ('SWITCH', 'Switch'), ('XBOX_ONE', 'Xbox One')], max_length=10)),
                ('release_date', models.DateField()),
                ('owned', models.BooleanField(default=True)),
                ('watched', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
